"use client";

import { ExperimentMeta } from "@/types";
import { DistanceGroup } from "@/lib/compute";
import AggregatesTable from "./AggregatesTable";
import RssiChart from "./RssiChart";
import Commentary from "./Commentary";
import { generateCommentary } from "@/lib/commentary";

interface Props {
    meta: ExperimentMeta;
    groups: DistanceGroup[];
}

export default function ReportView({ meta, groups }: Props) {
    const commentaryText = generateCommentary(groups, meta);

    return (
        <div className="max-w-4xl mx-auto bg-white p-8 print:p-0 print:max-w-none">

            {/* Header */}
            <div className="border-b-2 border-gray-800 pb-4 mb-6">
                <h1 className="text-3xl font-bold text-gray-900">{meta.title}</h1>
                <div className="flex justify-between mt-4 text-sm text-gray-600">
                    <div>
                        <p><span className="font-semibold">Student Name:</span> {meta.name || "____________________"}</p>
                        <p><span className="font-semibold">Date:</span> {new Date(meta.dateISO).toLocaleDateString()} {new Date(meta.dateISO).toLocaleTimeString()}</p>
                    </div>
                    <div className="text-right">
                        <p><span className="font-semibold">Location:</span> {meta.location || "____________________"}</p>
                        <p><span className="font-semibold">Target Band:</span> {meta.band}</p>
                    </div>
                </div>
            </div>

            {/* Equipment List */}
            <div className="mb-8">
                <h3 className="text-sm font-bold uppercase tracking-wide text-gray-500 mb-2">Equipment & Methodology</h3>
                <ul className="list-disc list-inside text-sm text-gray-700 space-y-1">
                    <li><strong>Device:</strong> Apple MacBook (macOS)</li>
                    <li><strong>Measurement Tool:</strong> Native macOS Wi-Fi Diagnostics (Option-click Menu / airport utility)</li>
                    <li><strong>Metric:</strong> RSSI (Received Signal Strength Indicator) in dBm</li>
                    <li><strong>Router:</strong> {meta.ssid ? `Access Point "${meta.ssid}"` : "Standard Wi-Fi Access Point"}</li>
                </ul>
            </div>

            {/* Main Content */}
            <div className="space-y-8">
                <AggregatesTable groups={groups} meta={meta} />

                <div className="break-inside-avoid">
                    <RssiChart groups={groups} meta={meta} />
                </div>

                <div className="break-inside-avoid">
                    <Commentary text={commentaryText} />
                </div>
            </div>

            {/* Footer */}
            <div className="mt-12 pt-4 border-t border-gray-200 text-center text-xs text-gray-400 print:block">
                Generated by RSSI Lab Logger • MIT PE
            </div>
        </div>
    );
}
